apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjek56TTFOVGt5T0N3aWFXRjBJam94TnpNM016VTFPVEk0ZlEuZkkyWEtqRHJjNUhQYUI2dHUyeHVQQnE3UTJ4Y19DdkQ1WkVGLWxvTlcySQo=
